urlSet:
  /customerServer/auth/login,
  /customerServer/auth/checkPermission,
  /customerServer/register,
  /customerServer/customer/phone/(.*),
  /customerServer/customer/customerName/(.*),
  /costomerServer/phone/login,
  /messageServer/message,
  /filmServer/films,
  /filmServer/film/(.*),
  /cinemaServer/cinemas,
  /filmServer/cinema/(.*)/films,
  /orderServer/schedule/(.*)/seat,
  /scheduleServer/cinema/(.*)/film/(.*),
  /(.*)/v2/api-docs


