# 权限请求白名单
# 先检测对应的模块,后检测请求具体路径
# 根据开发不断更新

adminSet:
  /customerServer/(.*),
  /filmServer/(.*),
  /cinemaServer/(.*),
  /scheduleServer/(.*)
userSet:
  /customerServer/(.*),
  /filmServer/film/(.*),
  /filmServer/films,
  /messageServer/message,
  /cinemaServer/cinemas,
  /filmServer/cinema/(.*)/films,
  /scheduleServer/cinema/(.*)/film/(.*),
  /orderServer/(.*),
  /commentServer/(.*),
  /payServer/(.*),
  /uploadServer/(.*)



