server:
  port: 8007

spring:
  application:
    name: mt-server-pay
  data:
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html

eureka:
  instance:
    instance-id: mt-server-pay
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


